#!/bin/sh

set -eu

F="${0%.sh}.go"
trap "rm -f '$F~'" EXIT
exec > "$F~"

cat <<EOT
package forms

//go:generate $0

import (
	"net/http"
)

// Code generated by $0 DO NOT EDIT
EOT

generate() {
	local N="$1" S="$2"
	local n="$N$S"
	local t="$(echo "$n" | tr A-Z a-z)"
	local extra_args= extra=
	shift 2

	if [ -n "${1:-}" ]; then
		extra_args=", $1"
		extra="$(echo "$1" | tr ',' '\n' | sed -e 's|^ \+||' -e 's| \+$||' | cut -d' ' -f1 | sed -e 's|^|, |' | tr -d '\n')"
	fi

	if [ -z "$S" ]; then
		extra_args="${extra_args:+$extra_args, }bitsize int"
		S=bitsize
	fi

cat <<EOT

func FormValue$n(req *http.Request, key string$extra_args) ($t, error, bool) {
	v, err, ok := FormValue$N(req, key$extra, $S)
	return $t(v), err, ok
}
EOT
}

generate Float 32
for x in Int Uint; do
	for n in '' 8 16 32; do
		generate "$x" "$n" "base int"
	done
done

if ! cmp -s "$F" "$F~"; then
	mv "$F~" "$F"
fi
