package forms

//go:generate ./generated.sh

import (
	"net/http"
)

// Code generated by ./generated.sh DO NOT EDIT

func FormValueFloat32(req *http.Request, key string) (float32, error, bool) {
	v, err, ok := FormValueFloat(req, key, 32)
	return float32(v), err, ok
}

func FormValueInt16(req *http.Request, key string, base int) (int16, error, bool) {
	v, err, ok := FormValueInt(req, key, base, 16)
	return int16(v), err, ok
}

func FormValueInt32(req *http.Request, key string, base int) (int32, error, bool) {
	v, err, ok := FormValueInt(req, key, base, 32)
	return int32(v), err, ok
}
